import httpx
import pytest
from fastapi import FastAPI

from holo.core.entities import RequestPerformer
from holo.ctx import ASGIContextMiddleware, context


# DECODED_MACHINE_KEY_JWT:
# {
#   "exp": 1658913145,
#   "iat": 1658913085,
#   "iss": "http://auth.auth",
#   "sub": "15676ad1-8f9b-593e-83f7-a3a7e20aae7c",
#   "type": "machine",
#   "client_id": "",
#   "partner_id": "",
#   "original_token": ""
# }
ENCODED_MACHINE_KEY_JWT = "eyJhbGciOiJFUzI1NiIsImtpZCI6IjFjOGJlNDYiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE2NTg5MTMxNDUsImlhdCI6MTY1ODkxMzA4NSwiaXNzIjoiaHR0cDovL2F1dGguYXV0aCIsInN1YiI6IjE1Njc2YWQxLThmOWItNTkzZS04M2Y3LWEzYTdlMjBhYWU3YyIsInR5cGUiOiJtYWNoaW5lIiwiY2xpZW50X2lkIjoiIiwicGFydG5lcl9pZCI6IiIsIm9yaWdpbmFsX3Rva2VuIjoiIn0.SjT4WLiiERMIHpcU8-htkWAe0S4PneRuNklrJ0ZurjPhvYITumxwGs9K3uj1qkzOhO93sFo5VvkDN9XRb1aeiw"  # noqa
# DECODED_USER_JWT (generated by scripts/fake_jwt.py):
# {
#     "type": "user",
#     "sub": "c6fa0410-1ba2-4ab0-a460-2369a248883b",
#     "original_token": "q18JLOJFB_Q78UOXvYURok18e-dq2ZV-HJ40Dv6CHpc",
#     "client_id": "c92cda48-fcbd-46af-bd27-d40e2b6e5d99",
#     "partner_id": None,
#     "portal_partner_id": "5cfe29b5-d49e-4320-91e2-0ded54384c65",
#     "portal_url": "https://partner.voipgrid.nl",
#     "wiki_url": "https://wiki.voipgrid.nl/index.php/",
#     "first_name": "John",
#     "preposition": "",
#     "last_name": "Doe",
# }
ENCODED_USER_JWT = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoidXNlciIsInN1YiI6ImM2ZmEwNDEwLTFiYTItNGFiMC1hNDYwLTIzNjlhMjQ4ODgzYiIsIm9yaWdpbmFsX3Rva2VuIjoicTE4SkxPSkZCX1E3OFVPWHZZVVJvazE4ZS1kcTJaVi1ISjQwRHY2Q0hwYyIsImNsaWVudF9pZCI6ImM5MmNkYTQ4LWZjYmQtNDZhZi1iZDI3LWQ0MGUyYjZlNWQ5OSIsInBhcnRuZXJfaWQiOm51bGwsInBvcnRhbF9wYXJ0bmVyX2lkIjoiNWNmZTI5YjUtZDQ5ZS00MzIwLTkxZTItMGRlZDU0Mzg0YzY1IiwicG9ydGFsX3VybCI6Imh0dHBzOi8vcGFydG5lci52b2lwZ3JpZC5ubCIsIndpa2lfdXJsIjoiaHR0cHM6Ly93aWtpLnZvaXBncmlkLm5sL2luZGV4LnBocC8iLCJmaXJzdF9uYW1lIjoiSm9obiIsInByZXBvc2l0aW9uIjoiIiwibGFzdF9uYW1lIjoiRG9lIn0.HkJLKHn-wgEN4VUPb7nHxolJ4bvyHqEWOCMvLmQSZ9Y"  # noqa


@pytest.fixture
def fastapi_app() -> FastAPI:
    """
    Returns FastAPI app initialized with ASGIContextMiddleware.
    """
    app = FastAPI()
    app.add_middleware(ASGIContextMiddleware)
    return app


@pytest.fixture
def async_client(fastapi_app) -> httpx.AsyncClient:
    """
    Returns AsyncClient initialized with FastAPI app.
    """
    return httpx.AsyncClient(transport=httpx.ASGITransport(app=fastapi_app), base_url="http://testserver", timeout=2)


async def test_middleware_with_user(fastapi_app, async_client) -> None:
    """
    Test auth middleware with user JWT token works.
    """

    @fastapi_app.get("/auth-info")
    async def auth_info() -> dict:
        return {
            **context.request_performer.model_dump(),
            "original_token": context.request_performer.original_token.get_secret_value(),
        }

    async with async_client:
        response = await async_client.get("/auth-info", headers={"Authorization": f"Bearer {ENCODED_USER_JWT}"})

    assert response.status_code == 200
    assert response.json() == {
        "id": "c6fa0410-1ba2-4ab0-a460-2369a248883b",
        "type": "user",
        "client_id": "c92cda48-fcbd-46af-bd27-d40e2b6e5d99",
        "partner_id": None,
        "original_token": "q18JLOJFB_Q78UOXvYURok18e-dq2ZV-HJ40Dv6CHpc",
        "portal_partner_id": "5cfe29b5-d49e-4320-91e2-0ded54384c65",
        "portal_url": "https://partner.voipgrid.nl",
        "wiki_url": "https://wiki.voipgrid.nl/index.php/",
        "first_name": "John",
        "preposition": "",
        "last_name": "Doe",
    }


async def test_middleware_with_machine_key(fastapi_app, async_client) -> None:
    """
    Test auth middleware with machine token works.
    """

    @fastapi_app.get("/auth-info")
    async def auth_info() -> RequestPerformer | None:
        return context.request_performer

    async with async_client:
        response = await async_client.get("/auth-info", headers={"Authorization": f"Bearer {ENCODED_MACHINE_KEY_JWT}"})

    assert response.status_code == 200
    assert response.json() == {
        "id": "15676ad1-8f9b-593e-83f7-a3a7e20aae7c",
        "type": "machine",
        "client_id": None,
        "partner_id": None,
        "original_token": "",
        "portal_partner_id": None,
        "portal_url": None,
        "wiki_url": None,
        "first_name": None,
        "preposition": None,
        "last_name": None,
    }


async def test_middleware_malformed_header_format(async_client) -> None:
    """
    Test auth middleware with malformed header returns a 400 status code.
    """
    async with async_client:
        for header_value in (
            ENCODED_MACHINE_KEY_JWT,
            f"Basic {ENCODED_MACHINE_KEY_JWT}",
            f"Bearer {ENCODED_MACHINE_KEY_JWT} something",
        ):
            response = await async_client.get("/info", headers={"Authorization": header_value})
            assert response.status_code == 400
            assert response.text == "malformed Authorization header, use: Bearer ENCODED_JWT_TOKEN"


async def test_middleware_malformed_jwt(async_client) -> None:
    """
    Test auth middleware with malformed jwt returns a 400 status code.
    """
    async with async_client:
        response = await async_client.get("/info", headers={"Authorization": "Bearer not_encoded_jwt_string"})

    assert response.status_code == 400
    assert response.text == "malformed Authorization header, use: Bearer ENCODED_JWT_TOKEN"
